### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by FlamingClaw** [KuromeSama6/Autosu#3] opened 2024-01-10 22:02 UTC
Whenever I click Cmd (start autopilot - full command) on the overlay, and go back to the game, it doesn't work at all. Is there a tutorial that shows how the bot works?

**Comment by KuromeSama6** [comment] 2024-01-14 13:29
I have not written much documentation on this, nor have been maintaining this project recently. I will work on documentation soon.

In the mean time, try doing the following in order:
1. Click CMD
2. Move your mouse cursor to the bottom right of the screen (where the start button in osu usually is), and click once. You should hear a sound.
3. After the beatmap has started, move the pointer to the position of the first note, and press C on your keyboard when the first note hits. There should be another sound. Autopilot should start from this point. Pressing HOME and bringing up the panel you should see several green lights.

If for some reason the cursor refuses to move, try closing out of Autosu by pressing SHIFT+END, and repeating the above steps. I am able to reproduce this issue but I am still investigating the cause of it.

**Comment by ivixxxxxxx** [comment] 2024-02-06 02:45
> I have not written much documentation on this, nor have been maintaining this project recently. I will work on documentation soon.
> 
> In the mean time, try doing the following in order:
> 
> 1. Click CMD
> 2. Move your mouse cursor to the bottom right of the screen (where the start button in osu usually is), and click once. You should hear a sound.
> 3. After the beatmap has started, move the pointer to the position of the first note, and press C on your keyboard when the first note hits. There should be another sound. Autopilot should start from this point. Pressing HOME and bringing up the panel you should see several green lights.
> 
> If for some reason the cursor refuses to move, try closing out of Autosu by pressing SHIFT+END, and repeating the above steps. I am able to reproduce this issue but I am still investigating the cause of it.

any progress on this?

**Comment by KuromeSama6** [comment] 2024-02-06 02:47
No, not yet. I am trying to figure out why the mouse cursor is not being moved on some occasions. I plan to get a tutorial video uploaded soon.

**Comment by ivixxxxxxx** [comment] 2024-02-06 02:50
> No, not yet. I am trying to figure out why the mouse cursor is not being moved on some occasions. I plan to get a tutorial video uploaded soon.

bettt 🙏

**Comment by KuromeSama6** [comment] 2024-02-06 15:09
Update - demo video is uploaded. Check README.md.

**Comment by ivixxxxxxx** [comment] 2024-02-08 10:50
> Update - demo video is uploaded. Check README.md.

you should probably close this issue then

**Comment by ezn1hero** [comment] 2024-05-18 13:02
Hi, what to do when I choose any map, it gives me in choose betmap: Variation:Not selected
![Screenshot (2)](https://github.com/KuromeSama6/Autosu/assets/170183154/c40d668f-c03b-40db-84f2-234277318d60)

**Comment by KuromeSama6** [comment] 2024-05-22 14:49
Click on any of the difficulty levels on the "Difficulty Select" panel to the right.

**Comment by ezn1hero** [comment] 2024-05-26 15:02
I'm already try this

**Comment by KuromeSama6** [comment] 2024-06-06 12:39
This issue is closed due to having too many complaints from different individuals. Please open a seperate issue for each problem encountered.

**Closed as completed by KuromeSama6** 2024-06-06 12:39 UTC
